version: '3.8'

services:
  # ==========================================
  # 1. BANCO DE DADOS POSTGRES (Exclusivo Evo)
  # ==========================================
  postgres-evo:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=evo_user
      - POSTGRES_PASSWORD=senha_banco_evo
      - POSTGRES_DB=evolution_db
    volumes:
      - evo_db_data:/var/lib/postgresql/data
    networks:
      - evolution_internal
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s

  # ==========================================
  # 2. REDIS (Exclusivo Evo)
  # ==========================================
  redis-evo:
    image: redis:7-alpine
    networks:
      - evolution_internal
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s

  # ==========================================
  # 3. EVOLUTION API GO
  # ==========================================
  evolution-api:
    image: evoapicloud/evolution-go:0.7.1 # <-- Imagem e repositório atualizados!
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      # --- Configurações Básicas ---
      - SERVER_PORT=8080
      - CLIENT_NAME=evolution
      - SERVER_URL=http://192.168.1.200:8080
      - GLOBAL_API_KEY=sua_senha_super_secreta_aqui
      - TZ=America/Sao_Paulo

      # --- Conexão com Banco de Dados ---
      - POSTGRES_AUTH_DB=postgresql://evo_user:senha_banco_evo@postgres-evo:5432/evolution_db?sslmode=disable
      - POSTGRES_USERS_DB=postgresql://evo_user:senha_banco_evo@postgres-evo:5432/evolution_db?sslmode=disable
      
      # --- Conexão com Redis ---
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis-evo:6379/1
      - WEBSOCKET_REDIS_ENABLED=true
      - WEBSOCKET_REDIS_URI=redis://redis-evo:6379/1
      - WEBHOOK_GLOBAL_ENABLED=false 
      
    volumes:
      - evo_instances_data:/evolution/instances
    networks:
      - evolution_internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 10s

volumes:
  evo_db_data:
  evo_instances_data:

networks:
  evolution_internal:
    driver: overlay