version: '3.8'

services:
  # ==========================================
  # 1. BANCO DE DADOS POSTGRES
  # ==========================================
  postgres-evo:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mudar_senha_depois # Usei uma senha diferente para forçar o reconhecimento
      - POSTGRES_DB=evogo_auth
    volumes:
      - evo_db_data:/var/lib/postgresql/data
    networks:
      - evolution_internal
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s

  # ==========================================
  # 2. REDIS
  # ==========================================
  redis-evo:
    image: redis:7-alpine
    networks:
      - evolution_internal
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # ==========================================
  # 3. EVOLUTION API GO
  # ==========================================
  evolution-api:
    image: evoapicloud/evolution-go:0.7.1
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      - SERVER_PORT=8080
      - CLIENT_NAME=evolution
      - GLOBAL_API_KEY=sua_chave_global
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=sua_chave_global
      
      # URIs de conexão atualizadas com a nova senha
      - POSTGRES_AUTH_DB=postgresql://postgres:mudar_senha_depois@postgres-evo:5432/evogo_auth?sslmode=disable
      - POSTGRES_USERS_DB=postgresql://postgres:mudar_senha_depois@postgres-evo:5432/evogo_auth?sslmode=disable
      
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis-evo:6379/1
      - WEBSOCKET_REDIS_ENABLED=true
      - WEBSOCKET_REDIS_URI=redis://redis-evo:6379/1

      - DATABASE_SAVE_MESSAGES=false
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - WEBHOOK_GLOBAL_ENABLED=false
      - WEBHOOK_EVENTS_ENABLED=false
      - WADEBUG=INFO
      - LOGTYPE=console
    networks:
      - evolution_internal
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  evo_db_data:
  evo_instances_data:

networks:
  evolution_internal:
    driver: overlay